package com.aniob.core.domain

/**
 * Atomic action generated by the planner or replay engine for single-step execution.
 * Exactly one action is executed per step.
 */
sealed class AniobAction {
    abstract val thought: String

    data class Click(
        val targetNodeId: Int,
        val x: Int = 0,
        val y: Int = 0,
        override val thought: String = "Clicking element $targetNodeId"
    ) : AniobAction()

    data class InputText(
        val targetNodeId: Int,
        val text: String,
        override val thought: String = "Typing text into element $targetNodeId"
    ) : AniobAction()

    data class Swipe(
        val direction: SwipeDirection,
        val distancePx: Int = 600,
        override val thought: String = "Swiping $direction"
    ) : AniobAction()

    data class PressKey(
        val key: KeyType,
        override val thought: String = "Pressing $key key"
    ) : AniobAction()

    data class Wait(
        val durationMs: Long = 1000L,
        override val thought: String = "Waiting ${durationMs}ms for UI to settle"
    ) : AniobAction()

    data class Finish(
        val summary: String = "Task completed successfully",
        override val thought: String = "Goal accomplished"
    ) : AniobAction()

    data class Fail(
        val reason: String,
        override val thought: String = "Execution failed: $reason"
    ) : AniobAction()
}

enum class SwipeDirection {
    UP, DOWN, LEFT, RIGHT
}

enum class KeyType {
    BACK, HOME, ENTER, RECENTS
}
