package com.aniob.core.skills

import com.aniob.core.domain.AniobAction

/**
 * Distills repeated, verified execution trajectories into DRAFT declarative skills (Skill Format v2.1).
 * Requires >= 3 successful runs with matching selector-chain shape signatures.
 * Includes security canary checks rejecting instruction-shaped text in slots.
 * Generated drafts require human PR review and cannot be auto-merged.
 */
class AniobSkillDistiller {

    data class TrajectoryStep(
        val stepIndex: Int,
        val action: AniobAction,
        val selectorShape: String,
        val success: Boolean
    )

    data class RecordedTrajectory(
        val taskId: String,
        val prompt: String,
        val steps: List<TrajectoryStep>,
        val overallSuccess: Boolean
    ) {
        fun shapeSignature(): String {
            return steps.joinToString("->") { "${it.action.toolName}:${it.selectorShape}" }
        }
    }

    private val trajectoryHistory = mutableListOf<RecordedTrajectory>()

    // Security canary patterns that reject prompt injection in candidate slots
    private val CANARY_INJECTION_PATTERNS = listOf(
        Regex("(?i)ignore\\s+(?:all\\s+)?previous\\s+instructions"),
        Regex("(?i)system\\s+prompt"),
        Regex("(?i)eval\\s*\\("),
        Regex("(?i)<script"),
        Regex("(?i)override\\s+safety"),
        Regex("(?i)act\\s+as\\s+(?:an?\\s+)?admin")
    )

    fun recordTrajectory(trajectory: RecordedTrajectory) {
        if (trajectory.overallSuccess && trajectory.steps.isNotEmpty()) {
            trajectoryHistory.add(trajectory)
        }
    }

    /**
     * Attempts distillation for a given prompt task.
     * Returns DRAFT YAML if >= 3 matching trajectories exist and pass security canaries.
     */
    fun distillIfReady(prompt: String): String? {
        val matchingRuns = trajectoryHistory.filter {
            it.prompt.equals(prompt, ignoreCase = true) && it.overallSuccess
        }

        if (matchingRuns.size < 3) return null

        // Group by selector-chain shape signature
        val signatureGroups = matchingRuns.groupBy { it.shapeSignature() }
        val dominantGroup = signatureGroups.maxByOrNull { it.value.size } ?: return null

        if (dominantGroup.value.size < 3) return null

        val sample = dominantGroup.value.first()

        // Security Canary Check: Check all text fields for prompt injection
        for (step in sample.steps) {
            val candidateText = when (val a = step.action) {
                is AniobAction.InputText -> a.text
                is AniobAction.ConfirmWithUser -> a.message
                else -> ""
            }

            for (pattern in CANARY_INJECTION_PATTERNS) {
                if (pattern.containsMatchIn(candidateText)) {
                    // Security canary tripped! Reject distillation
                    return null
                }
            }
        }

        // Generate DRAFT YAML (v2.1)
        val skillName = prompt.trim().lowercase().replace(Regex("[^a-z0-9]+"), "_").take(32)

        return buildString {
            appendLine("# AUTOGENERATED DRAFT SKILL - REQUIRES HUMAN PR APPROVAL")
            appendLine("name: \"draft_$skillName\"")
            appendLine("version: \"2.1\"")
            appendLine("description: \"Autogenerated skill from 3 verified executions of: $prompt\"")
            appendLine("risk_tier: \"MEDIUM\"")
            appendLine("confirmation_required: false")
            appendLine("triggers:")
            appendLine("  - \"${prompt.trim().lowercase()}\"")
            appendLine("steps:")
            sample.steps.forEach { s ->
                appendLine("  - step: ${s.stepIndex}")
                appendLine("    action: \"${s.action.toolName}\"")
                appendLine("    description: \"${s.action.thought}\"")
                if (s.action is AniobAction.InputText) {
                    appendLine("    text: \"${s.action.text}\"")
                }
            }
        }
    }
}
